/**
 * RepoReel — Closing Scene
 * Wrap up with repo URL and tech summary.
 */
import React from "react";
import {
  AbsoluteFill,
  useCurrentFrame,
  useVideoConfig,
  spring,
  interpolate,
} from "remotion";
import { useTheme } from "../themes/ThemeProvider";
import { NoiseBackground } from "../components/NoiseBackground";

export const ClosingScene: React.FC<{
  content: { repo_url?: string; built_with?: string };
  background_variant?: string;
}> = ({ content, background_variant = "gradient" }) => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();
  const theme = useTheme();

  const mainProgress = spring({ frame, fps, config: { damping: 14, stiffness: 70 } });
  const urlProgress = spring({
    frame: Math.max(0, frame - 12),
    fps,
    config: { damping: 16, stiffness: 80 },
  });
  const watermarkProgress = spring({
    frame: Math.max(0, frame - 20),
    fps,
    config: { damping: 18, stiffness: 60 },
  });

  // Fade out
  const exitStart = Math.max(0, durationInFrames - 15);
  const exitOpacity = interpolate(frame, [exitStart, durationInFrames], [1, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  return (
    <AbsoluteFill>
      <NoiseBackground variant={background_variant as any} />
      <AbsoluteFill
        style={{
          justifyContent: "center",
          alignItems: "center",
          padding: 80,
          opacity: exitOpacity,
        }}
      >
        {/* GitHub URL */}
        <div
          style={{
            fontSize: 38,
            fontWeight: 600,
            fontFamily: theme.fonts.code,
            color: theme.colors.accent,
            padding: "18px 40px",
            borderRadius: 14,
            border: `2px solid ${theme.colors.accent}50`,
            backgroundColor: `${theme.colors.cardBg}cc`,
            opacity: mainProgress,
            transform: `scale(${0.85 + mainProgress * 0.15})`,
          }}
        >
          {content.repo_url || "github.com"}
        </div>

        {/* Built with */}
        {content.built_with && (
          <div
            style={{
              fontSize: 24,
              fontFamily: theme.fonts.body,
              color: theme.colors.textMuted,
              marginTop: 30,
              opacity: urlProgress,
              transform: `translateY(${(1 - urlProgress) * 20}px)`,
            }}
          >
            Built with {content.built_with}
          </div>
        )}

        {/* RepoReel watermark */}
        <div
          style={{
            position: "absolute",
            bottom: 60,
            fontSize: 18,
            fontFamily: theme.fonts.body,
            color: `${theme.colors.textMuted}80`,
            opacity: watermarkProgress,
            letterSpacing: "3px",
            textTransform: "uppercase",
          }}
        >
          Generated by RepoReel
        </div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};
