"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

function extractRepoName(url) {
  if (!url) return "Unknown";
  const parts = url.replace(/\/$/, "").split("/");
  if (parts.length >= 2) {
    return `${parts[parts.length - 2]}/${parts[parts.length - 1]}`;
  }
  return url;
}

function timeAgo(dateStr) {
  if (!dateStr) return "";
  const date = typeof dateStr === "number" ? new Date(dateStr * 1000) : new Date(dateStr);
  const now = new Date();
  const diffMs = now - date;
  const diffMin = Math.floor(diffMs / 60000);
  if (diffMin < 1) return "just now";
  if (diffMin < 60) return `${diffMin}m ago`;
  const diffHr = Math.floor(diffMin / 60);
  if (diffHr < 24) return `${diffHr}h ago`;
  const diffDay = Math.floor(diffHr / 24);
  return `${diffDay}d ago`;
}

// Theme accent colors for visual badges
const THEME_COLORS = {
  "Dark Cinematic": "#6c63ff",
  "Neon Cyberpunk": "#ff00ff",
  "Minimal Light": "#3b82f6",
  "Terminal Green": "#00ff41",
  "Ocean Depth": "#64ffda",
};

export default function GalleryPage() {
  const [entries, setEntries] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const backendUrl =
      process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:8000";

    async function fetchGallery() {
      try {
        const res = await fetch(`${backendUrl}/api/gallery`);
        if (res.ok) {
          let data = await res.json();

          // Merge with session-stored user videos
          try {
            const sessionVideos = JSON.parse(
              sessionStorage.getItem("automotion_gallery") || "[]"
            );
            if (sessionVideos.length > 0) {
              data = [...sessionVideos, ...data];
            }
          } catch {
            // sessionStorage unavailable
          }

          setEntries(data);
        }
      } catch {
        // backend offline — still show session entries
        try {
          const sessionVideos = JSON.parse(
            sessionStorage.getItem("automotion_gallery") || "[]"
          );
          setEntries(sessionVideos);
        } catch {
          // nothing to show
        }
      } finally {
        setLoading(false);
      }
    }

    fetchGallery();

    // Auto-refresh every 30 seconds
    const interval = setInterval(fetchGallery, 30000);
    return () => clearInterval(interval);
  }, []);

  return (
    <main>
      {/* Nav */}
      <nav className="nav">
        <div className="container nav-inner">
          <Link href="/" className="nav-logo">
            AutoMotion
          </Link>
          <a href="/gallery" className="nav-link" style={{ fontWeight: 600 }}>
            Gallery
          </a>
        </div>
      </nav>

      <div className="container">
        {/* Header */}
        <section className="gallery-header animate-enter">
          <h1 className="gallery-title">Video Gallery</h1>
          <p className="gallery-subtitle">
            Sample explainer videos generated by AutoMotion. Each video is
            automatically created from a public GitHub repository.
          </p>
        </section>

        {/* Loading */}
        {loading && (
          <div className="gallery-empty animate-enter">
            <div className="spinner" style={{ width: 24, height: 24 }} />
            <p>Loading gallery...</p>
          </div>
        )}

        {/* Empty state */}
        {!loading && entries.length === 0 && (
          <div className="gallery-empty animate-enter">
            <p>No videos generated yet.</p>
            <Link href="/" className="btn-primary" style={{ marginTop: 16 }}>
              Generate your first video →
            </Link>
          </div>
        )}

        {/* Grid */}
        {!loading && entries.length > 0 && (
          <div className="gallery-grid animate-enter" style={{ animationDelay: "100ms" }}>
            {entries.map((entry, i) => {
              const repoName = extractRepoName(entry.repo_url);
              const themeColor = THEME_COLORS[entry.theme] || "#888";
              const isSample = entry.is_sample;

              return (
                <div key={entry.job_id || i} className="gallery-card">
                  {/* Thumbnail area */}
                  <div
                    className="gallery-thumb"
                    style={{
                      background: entry.thumbnail_url
                        ? "#000"
                        : `linear-gradient(135deg, ${themeColor}22 0%, ${themeColor}08 100%)`,
                    }}
                  >
                    {entry.thumbnail_url ? (
                      <img
                        src={`${process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:8000"}${entry.thumbnail_url}`}
                        alt={`${repoName} thumbnail`}
                        style={{ width: "100%", height: "100%", objectFit: "cover" }}
                      />
                    ) : (
                      <div className="gallery-thumb-icon">🎬</div>
                    )}
                    {isSample && (
                      <span className="gallery-sample-badge">Sample</span>
                    )}
                  </div>

                  {/* Meta */}
                  <div className="gallery-meta">
                    <div className="gallery-repo">{repoName}</div>
                    <div className="gallery-meta-row">
                      <span
                        className="gallery-theme-badge"
                        style={{
                          borderColor: themeColor,
                          color: themeColor,
                        }}
                      >
                        {entry.theme || "Auto"}
                      </span>
                      <span className="gallery-time">
                        {timeAgo(entry.created_at)}
                      </span>
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="gallery-actions">
                    {!isSample && entry.video_url ? (
                      <Link
                        href={`/generate?job_id=${entry.job_id}&repo_url=${encodeURIComponent(entry.repo_url)}`}
                        className="btn-primary gallery-btn"
                      >
                        Watch
                      </Link>
                    ) : (
                      <Link
                        href={`/?prefill=${encodeURIComponent(entry.repo_url)}`}
                        className="btn-secondary gallery-btn"
                      >
                        Generate
                      </Link>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </main>
  );
}
