Get-ChildItem -Path "j:\Orion Build Hackathon\repoReel\remotion\src" -Include "*.tsx","*.ts" -Recurse | ForEach-Object {
    $content = Get-Content $_.FullName -Raw
    $newContent = $content -replace 'RepoReel —', 'AutoMotion —'
    if ($content -ne $newContent) {
        Set-Content -Path $_.FullName -Value $newContent -NoNewline
        Write-Host ("Updated: " + $_.Name)
    }
}

# Also fix "Generated by RepoReel" watermark in ClosingScene.tsx
$closingPath = "j:\Orion Build Hackathon\repoReel\remotion\src\scenes\ClosingScene.tsx"
$content = Get-Content $closingPath -Raw
$content = $content -replace 'Generated by RepoReel', 'Generated by AutoMotion'
$content = $content -replace '\{/\* RepoReel watermark \*\/', '{/* AutoMotion watermark */'
Set-Content -Path $closingPath -Value $content -NoNewline
Write-Host "Updated ClosingScene watermark"

# Fix Root.tsx default props
$rootPath = "j:\Orion Build Hackathon\repoReel\remotion\src\Root.tsx"
$content = Get-Content $rootPath -Raw
$content = $content -replace 'Welcome to RepoReel', 'Welcome to AutoMotion'
$content = $content -replace 'content: \{ title: "RepoReel"', 'content: { title: "AutoMotion"'
# Keep the composition id="RepoReel" and component names unchanged (they are programmatic references)
Set-Content -Path $rootPath -Value $content -NoNewline
Write-Host "Updated Root.tsx defaults"
